package com.example.project.Airport;
import java.util.ArrayList;

public class Airport  {
    /** A list of the flights into and out of this airport
     *  Guaranteed not to be null and to contain only non-null entries
     */
    private ArrayList<Flight> allFlights;

    public Airport(ArrayList<Flight> flights) {
        allFlights = flights; 
    }

    public ArrayList<Flight> getAllFlights() {
        return allFlights;
    }
 
    /** Returns the revenue generated by all flights at the airport,
     *  as described in part (a)
     */
    public double getTotalRevenue() {
        /* to be implemented in part (a) */
        double total = 0.0;
        int len = allFlights.size();
        for (int i = 0; i < len; i ++) {
            int people = allFlights.get(i).getNumPassengers();
            if (people > allFlights.get(i).getCapacity()) {
                people = allFlights.get(i).getCapacity();
            }
    
            total += people * allFlights.get(i).getPrice();    
        }
        return total;
    }

    /** Updates the list of flights by removing certain flights and
     *  returns the total number of passengers whose flights were removed,
     *  as described in part (b)
     */
    public int updateFlights() {
        int removed = 0;

        for (int i = allFlights.size() - 1; i >= 0; i --) {
            Flight one = allFlights.get(i);
            int people = one.getNumPassengers();
            if (people < one.getCapacity() * 0.2) {
                removed += people;
                allFlights.remove(i);
            }

        }
        return removed;
    }
}